slam_toolbox:
  ros__parameters:
    use_sim_time: True
    mode: "mapping"  # Si estás generando el mapa
    scan_topic: "/scan"
    map_file_name: ""
    resolution: 0.05
    max_laser_range: 30.0
    minimum_time_interval: 1.0
    transform_publish_period: 0.05
    map_update_interval: 5.0
    publish_to_scan_matcher_transform: True
    publish_pose: True
    use_scan_matching: True
    use_scan_barycenter: False
    map_frame: "map"
    base_frame: "base_link"
    odom_frame: "odom"
    provide_odom_frame: False  # No queremos que slam_toolbox maneje la odometría
    publish_odom_to_base: False  # Si no usas odometría, desactiva esto
